<?php

declare(strict_types=1);

namespace VoicemailAi\Mail;

use VoicemailAi\Audio\AudioFile;

/**
 * Voicemail notification as generated by Asterisk app_voicemail.
 */
final readonly class Voicemail
{
    /**
     * @param list<Address> $to
     */
    public function __construct(
        public ?Address $from,
        public array $to,
        public string $subject,
        public string $body,
        public ?string $callerId = null,
        public ?string $callerName = null,
        public ?string $date = null,
        public ?string $messageId = null,
        public ?AudioFile $audio = null,
    ) {}

    /**
     * Human readable caller, e.g. "John Doe <0612345678>".
     */
    public function caller(): ?string
    {
        if ($this->callerName !== null && $this->callerId !== null && $this->callerName !== $this->callerId) {
            return sprintf('%s <%s>', $this->callerName, $this->callerId);
        }

        return $this->callerId ?? $this->callerName;
    }
}
