<?php

/**
 * Copy this file to config/config.php and adjust the values.
 *
 * The file contains the OVHcloud API token: keep it readable by the asterisk
 * user only (chown root:asterisk config.php && chmod 640 config.php).
 */

declare(strict_types=1);

return [
    'ovh' => [
        // OpenAI compatible base URL of OVHcloud AI Endpoints.
        'base_url' => 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1',
        // Access token created in the OVHcloud Control Panel (Public Cloud > AI Endpoints).
        // Without a token, requests are anonymous and limited (10 MB / 60 s of audio).
        'token' => '',
        'model' => 'whisper-large-v3',
        // ISO-639-1 code, or null for automatic language detection.
        'language' => 'fr',
        // Optional hint to guide the transcription (vocabulary, company names...).
        'prompt' => null,
        'temperature' => 0.0,
        // Timeout of one HTTP request, in seconds.
        'timeout' => 120,
        // Number of retries on network errors, HTTP 429 and 5xx.
        'max_retries' => 2,
    ],
    'audio' => [
        // The email attachment is converted to MP3 (the original WAV is still used
        // for the transcription). Set to null to attach the original WAV.
        'ffmpeg' => '/usr/bin/ffmpeg',
        // MP3 bitrate, 32k is plenty for telephone audio.
        'mp3_bitrate' => '32k',
    ],
    'mail' => [
        // Postfix sendmail binary. Never point this to the voicemail mailcmd itself.
        'sendmail' => '/usr/sbin/sendmail',
        // null keeps the "From" generated by Asterisk (FreePBX "Email From" setting).
        'from_address' => null,
        'from_name' => null,
        // Envelope sender (sendmail -f), null lets Postfix decide.
        'envelope_sender' => null,
        'subject_prefix' => '',
        // Attach the recording (MP3) to the email. It is always attached when the transcription fails.
        'attach_audio' => true,
        // Custom templates (null = templates/ directory of the project).
        'html_template' => null,
        'text_template' => null,
        // Per voicemail box overrides (box number = ${VM_MAILBOX}), e.g. one per phone number.
        // Allowed keys: from_address, from_name, subject_prefix, attach_audio, html_template,
        // text_template. Missing keys keep the values above.
        'mailboxes' => [
            // '1001' => [
            //     'from_name' => 'Service client',
            //     'subject_prefix' => '[SAV] ',
            //     'html_template' => '/etc/voicemail-ai/sav.html.php',
            //     'text_template' => '/etc/voicemail-ai/sav.txt.php',
            // ],
        ],
    ],
    'log' => [
        // Messages are sent to syslog (journalctl -t voicemail-ai).
        'ident' => 'voicemail-ai',
        'debug' => false,
    ],
];
